### PR TITLE
Add `mps_add` function

### PR DESCRIPTION
**Pull request by MatthiasReumann**
### Changelog
- Add `mps_add` function (More or less a 1:1 copy of the [PyTeNet](https://github.com/cmendl/pytenet/blob/3cf9c3e72b7378b3dde6b3f029e2753f22ae06c8/pytenet/mps.py#L334) implementation)
- Add `test_mps_add` test function (Generate Random MPS ➡ `mps_add` ➡ Compare state-vectors)
- Update `README.md` (Add dependency installation instructions for MacOS)
- Add `.vscode/` to `.gitignore`

### CODE REVIEW

**Comment by cmendl** [comment]
Thanks for the nice work! Could you modify the pull request by additionally taking these suggestions into account?
- The data type of the logical output MPS should also be struct mps* (instead of a void pointer). Use allocate_empty_mps to allocate it inside mps_add.
- Try to rebase the new branch to the latest version of the main branch.
- For consistency, please start comments with lower-case and without a final dot.
- In the test, use a literal number instead of "site_array_len" (since "int site_array[site_array_len]" is not allowed in standard C).
- The test function "char* test_mps_add()" should come directly after char* test_mps_vdot() (to follow the same order as in mps.c)

**Comment by MatthiasReumann** [comment]
> Thanks for the nice work! Could you modify the pull request by additionally taking these suggestions into account?
> 
> * The data type of the logical output MPS should also be struct mps* (instead of a void pointer). Use allocate_empty_mps to allocate it inside mps_add.
> * Try to rebase the new branch to the latest version of the main branch.
> * For consistency, please start comments with lower-case and without a final dot.
> * In the test, use a literal number instead of "site_array_len" (since "int site_array[site_array_len]" is not allowed in standard C).
> * The test function "char* test_mps_add()" should come directly after char* test_mps_vdot() (to follow the same order as in mps.c)

Thanks for the feedback! I've updated the code accordingly.

**Comment by cmendl** [comment]
Thanks again! Minor additional point: the local variable qsite is allocated but not freed; actually, instead of allocating this array, one can directly pass psi->qsite to allocate_empty_mps (since it creates its own copy internally).

**Comment by MatthiasReumann** [comment]
> Thanks again! Minor additional point: the local variable qsite is allocated but not freed; actually, instead of allocating this array, one can directly pass psi->qsite to allocate_empty_mps (since it creates its own copy internally).

I've removed the `qsite` copying now, thanks!

**Comment by cmendl** [comment]
Final minor point: currently the automatic unit test does not run due to const qnumber qsite_chi[d] in the unit test; please use an explicit integer here as well, i.e., const qnumber qsite_chi[2]

**Comment by MatthiasReumann** [comment]
> Final minor point: currently the automatic unit test does not run due to const qnumber qsite_chi[d] in the unit test; please use an explicit integer here as well, i.e., const qnumber qsite_chi[2]

Ah yes, sorry for that.

**Comment by MatthiasReumann** [comment]
Interesting. Locally `ctest` works without any troubles. I will build and run the tests on `lxhalle` (or similar) soon and try to fix the unit test.

**Comment by cmendl** [comment]
There is a problem in the "qnumber_all_equal" assertions: the first argument should be the logical dimension instead of "ndim", for example, assert(qnumber_all_equal(chi_a.dim_logical[0], ...)). Also, in the unit test, the quantum number sector qnum_sector = encode_quantum_number_pair(q_pnum, q_spin) leads to MPS which are logical zero vectors (since the quantum number restriction cannot be satisfied); instead, you can set qnum_sector to a small integer.

**Comment by cmendl** [comment]
Thanks! I've now squash-merged the pull request into the main branch.

**Comment by MatthiasReumann** [comment]
Great - thanks for the patience and sorry for the hiccups!

**Pull request closed without merging**
